{dede:noteinfo notename="网页基础-Javascript/Ajax" channelid="1" macthtype="string"
	refurl="http://" sourcelang="gb2312" cosort="asc"
  isref="no" exptime="10" usemore="0" /}
{dede:listrule sourcetype="batch" rssurl="http://" regxurl="http://www.dedecms.com/knowledge/web-based/javascript-ajax/list_46_(*).html"
startid="1" endid="2" addv="1" urlrule="area" musthas="/knowledge/web-based/"
 nothas="" listpic="1" usemore="0"}
	{dede:addurls}{/dede:addurls}
	{dede:batchrule}{/dede:batchrule}
	{dede:regxrule}{/dede:regxrule}
	{dede:areastart}<div class="arc_list">{/dede:areastart}
	{dede:areaend}</div>{/dede:areaend}
{/dede:listrule}
