<?php
$z[0]=Array("noteinfo","",0,252);
$z[0][4]['notename']="天猫商品采集";
$z[0][4]['channelid']="6";
$z[0][4]['macthtype']="string";
$z[0][4]['refurl']="http://detail.tmall.com/item.htm?spm=a1z10.3.w17-737739803.11.Ti4BjM&id=21578412784&";
$z[0][4]['sourcelang']="gb2312";
$z[0][4]['cosort']="asc";
$z[0][4]['isref']="yes";
$z[0][4]['exptime']="10";
$z[0][4]['usemore']="0";
$z[1]=Array("listrule","\r\n    {dede:addurls}{/dede:addurls}\r\n    {dede:batchrule}{/dede:batchrule}\r\n    {dede:regxrule}{/dede:regxrule}\r\n    {dede:areastart}<ul class=\"shop-list\">{/dede:areastart}\r\n    {dede:areaend}<div class=\"pagination\">{/dede:areaend}\r\n",254,789);
$z[1][4]['sourcetype']="batch";
$z[1][4]['rssurl']="http://";
$z[1][4]['regxurl']="http://lcly.tmall.com/search.htm?spm=a1z10.3.w17-737739803.65.xM1vxS&search=y&viewType=list&orderType=newOn&pageNum=(*)";
$z[1][4]['startid']="1";
$z[1][4]['endid']="7";
$z[1][4]['addv']="1";
$z[1][4]['urlrule']="area";
$z[1][4]['musthas']="";
$z[1][4]['nothas']="show_review";
$z[1][4]['listpic']="1";
$z[1][4]['usemore']="0";

?>