<?php
$z[0]=Array("noteinfo","",0,180);
$z[0][4]['notename']="网页基础-Dreamweaver";
$z[0][4]['channelid']="1";
$z[0][4]['macthtype']="string";
$z[0][4]['refurl']="http://";
$z[0][4]['sourcelang']="gb2312";
$z[0][4]['cosort']="asc";
$z[0][4]['isref']="no";
$z[0][4]['exptime']="10";
$z[0][4]['usemore']="0";
$z[1]=Array("listrule","\r\n    {dede:addurls}{/dede:addurls}\r\n    {dede:batchrule}{/dede:batchrule}\r\n    {dede:regxrule}{/dede:regxrule}\r\n    {dede:areastart}<!--没有下一页-->\r\n</div>\r\n</div>{/dede:areastart}\r\n    {dede:areaend}<div class=\"pagination\">{/dede:areaend}\r\n",182,695);
$z[1][4]['sourcetype']="batch";
$z[1][4]['rssurl']="http://";
$z[1][4]['regxurl']="http://www.dedecms.com/knowledge/web-based/dreamweaver/list_47_(*).html";
$z[1][4]['startid']="1";
$z[1][4]['endid']="2";
$z[1][4]['addv']="1";
$z[1][4]['urlrule']="area";
$z[1][4]['musthas']="/knowledge/web-based/";
$z[1][4]['nothas']="";
$z[1][4]['listpic']="1";
$z[1][4]['usemore']="0";

?>