<?php
$z[0]=Array("sppage","<div class=\"pagebreak\">[内容]</div>",0,96);
$z[0][4]['sptype']="full";
$z[0][4]['srul']="1";
$z[0][4]['erul']="5";
$z[1]=Array("previewurl","http://www.dedecms.com/knowledge/web-based/html/2009/0929/880.html",98,199);
$z[2]=Array("keywordtrim","",201,238);
$z[3]=Array("descriptiontrim","",240,285);
$z[4]=Array("item","\r\n   {dede:match}<title>[内容]_织梦CMS</title>{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",287,459);
$z[4][4]['field']="title";
$z[4][4]['value']="";
$z[4][4]['isunit']="";
$z[4][4]['isdown']="";
$z[5]=Array("item","\r\n   {dede:match}{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",459,599);
$z[5][4]['field']="writer";
$z[5][4]['value']="";
$z[5][4]['isunit']="";
$z[5][4]['isdown']="";
$z[6]=Array("item","\r\n   {dede:match}{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",599,739);
$z[6][4]['field']="source";
$z[6][4]['value']="";
$z[6][4]['isunit']="";
$z[6][4]['isdown']="";
$z[7]=Array("item","\r\n   {dede:match}{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",739,880);
$z[7][4]['field']="pubdate";
$z[7][4]['value']="";
$z[7][4]['isunit']="";
$z[7][4]['isdown']="";
$z[8]=Array("item","\r\n   {dede:match}<div class=\"content\">[内容]<div class=\"pagebreak\">{/dede:match}\r\n   {dede:trim replace=\"\"}<a([^>]*)>(.*)</a>{/dede:trim}\r\n{dede:trim replace=\"\"}<script([^>]*)>(.*)</script>{/dede:trim}\r\n{dede:trim replace=\"\"}<!--(.*)-->{/dede:trim}\r\n{dede:trim replace=\"\"}<object([^>]*)>(.*)</object>{/dede:trim}\r\n{dede:trim replace=\"\"}<div([^.]*)>{/dede:trim}\r\n{dede:trim replace=\"\"}</div>{/dede:trim}\r\n   {dede:function}{/dede:function}\r\n",880,1389);
$z[8][4]['field']="body";
$z[8][4]['value']="";
$z[8][4]['isunit']="1";
$z[8][4]['isdown']="1";

?>